name: Check all solutions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DENO_DIR: deno_cache

jobs:
  check-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unlock git-crypt secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Run check-all task
        run: deno task check-all
